from datetime import datetime
import pandas as pd

file = r"data\raw\Seasonal_Food_Guide.csv"

df = pd.read_csv(file)

def print_veg_list(df):
    """Identifies the unique veggies in the dataframe and prints them in a format that can be copied/pasted into a dictionary."""

    unique_sfg_values = df["vegetable"].unique()

    print('mapper = {')
    for veg in unique_sfg_values:
        print(f'    "{veg}": "",')
    print('}')

mapper = {
    "apples": "Apple",
    "arugula": "Rocket",
    "asian-pears": "?",
    "asparagus": "Asparagus",
    "basil": "",
    "beets": "Beetroot",
    "black-eyed-peas": "",
    "blackberries": "Blackberry",
    "blueberries": "Blueberry",
    "bok-choy": "Bok Choy?",
    "boysenberries": "?",
    "brambles": "--BROAD-CATEGORY--",
    "broccoli": "Broccoli",
    "brussels-sprouts": "Brussels sprouts",
    "cabbage": "White cabbage",
    "cantaloupe": "Cantaloupe?",
    "cardoons": "Cardoon?",
    "carrots": "Carrot",
    "cauliflower": "Cauliflower",
    "celery": "Celery",
    "celery-root": "",
    "chard": "Swiss chard?",
    "cherries": "Cherry",
    "chicories": "?",
    "chili-peppers": "",
    "chives": "",
    "cilantro": "",
    "citrus": "--BROAD-CATEGORY--",
    "clementines": "Clementine",
    "collard-greens": "Collard greens?",
    "corn": "Corn",
    "cucumbers": "Cucumber",
    "edamame": "",
    "eggplant": "Aubergine",
    "endive": "Endive",
    "fava-beans": "",
    "fennel": "Fennel",
    "figs": "Fig",
    "garlic": "",
    "garlic-scapes": "",
    "gooseberries": "Gooseberries",
    "grapefruit": "Grapefruit",
    "grapes": "Grapes",
    "green-beans": "Green bean",
    "green-onions": "",
    "ground-cherries": "",
    "horseradish": "Horseradish?",
    "kale": "Kale",
    "kohlrabi": "Kohlrabi",
    "lamb's-quarters": "",
    "lavender": "",
    "leeks": "Leek",
    "lemons": "",
    "lettuce": "Lettuce",
    "lima-beans": "",
    "loquats": "Loquat?",
    "mandarins": "Mandarin oranges?",
    "melons": "--BROAD-CATEGORY--",
    "mint": "",
    "mushrooms": "",
    "mustard-greens": "",
    "nectarines": "Nectarine",
    "nettles": "",
    "okra": "Okra?",
    "onions": "",
    "oranges": "Orange",
    "oregano": "",
    "parsley": "",
    "parsnips": "Parsnip",
    "pawpaw": "Pawpaw?",
    "pea-shoots": "?",
    "peaches": "Peach",
    "pears": "Pear",
    "peas": "Peas",
    "pecans": "",
    "peppers": "--BROAD-CATEGORY--",
    "persimmons": "Persimmon",
    "plums": "Plum",
    "potatoes": "Potato",
    "pummelo": "?",
    "pumpkin": "Pumpkin",
    "purslane": "",
    "quince": "",
    "radicchio": "Radicchio?",
    "radishes": "Radish?",
    "rapini": "Rapini",
    "raspberries": "Raspberry",
    "rhubarb": "Rhubarb?",
    "rosemary": "",
    "rutabaga": "?",
    "sage": "",
    "shallots": "?",
    "shell-beans": "",
    "snap-peas": "?",
    "snow-peas": "?",
    "sorrel": "",
    "spinach": "Spinach",
    "sprouts": "",
    "strawberries": "Strawberry",
    "summer-squash": "Summer squash",
    "sunchokes": "",
    "sweet-potatoes": "Sweet potato",
    "tangerines": "",
    "tarragon": "",
    "thyme": "",
    "tomatillos": "?",
    "tomatoes": "Tomato",
    "turnips": "Turnip",
    "watercress": "?",
    "watermelon": "Watermelon",
    "winter-squash": "Winter squash",
    "yams": "Yam",
    "zucchini": "Zucchini",
    "apricots": "Apricot",
    "currants": "Currants",
    "dates": "Dates",
    "nopales": "Prickly pear",
    "pistachios": "",
    "salsify": "",
    "morels": "",
    "artichokes": "Artichoke",
    "avocados": "Avocado",
    "burdock": "Burdock",
    "cactus-pears": "",
    "cherimoyas": "Cherimoya",
    "chestnuts": "",
    "chickpeas": "",
    "fiddleheads": "Fiddleheads",
    "ginger": "",
    "guava": "Guava",
    "kiwi": "Kiwi",
    "kumquats": "?",
    "lemongrass": "",
    "limes": "",
    "mangoes": "Mango",
    "moringa": "?",
    "olives": "",
    "orach": "",
    "peanuts": "",
    "pigeon-peas": "",
    "pomegranates": "Pomegranate",
    "white-sapote": "?",
    "yacon": "Yacon",
    "longan": "??",
    "lychee": "Lychee",
    "malabar-spinach": "?",
    "passionfruit": "",
    "cranberries": "",
    "ramps": "",
    "papaya": "",
    "taro": "",
    "taro-leaf": "",
    "atemoya": "",
    "bananas": "",
    "black-sapote": "",
    "breadfruit": "",
    "caimito": "",
    "canistel": "",
    "coconut": "",
    "dragon-fruit": "",
    "jackfruit": "",
    "jicama": "",
    "mamey-sapote": "",
    "mamoncillo": "",
    "mysore-raspberries": "",
    "pineapple": "",
    "sapodilla": "",
    "starfruit": "",
    "sugarcane": "",
    "turmeric": "",
    "yuca": "",
    "bittermelon": "",
    "rambutan": "",
}

def assign_forkranger_names(df: pd.DataFrame, mapper: dict[str, str]):
    """Adds a column to the dataframe with mapped fork ranger names for the vegetables."""

    df["fork-ranger-name"] = df["vegetable"].apply(lambda x: mapper[x] if mapper[x] != "" else "-")
    df = df[["state", "vegetable", "fork-ranger-name", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]]

    return df

if __name__ == "__main__":

    # print_veg_list(df)

    start = datetime.now()
    df = assign_forkranger_names(df, mapper)
    print(datetime.now() - start)  # executes in 0.0023 seconds

    df.to_csv(r"data\raw\(temp) Seasonal_Food_Guide-assigned.csv", index=False)